---
name: Tree-Base
version: v0.10.2
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: a base class for trees
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Tree-Base
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://svn.scratchcomputing.com/Tree-Base/trunk
build_requires:
  Module::Build: 0.26
  Test::More: 0
requires:
  Scalar::Util: 0
configure_requires:
  Module::Build: 0.34
provides:
  Tree::Base:
    file: lib/Tree/Base.pm
    version: v0.10.2
  Tree::Base::Knob:
    file: lib/Tree/Base.pm
generated_by: Module::Build version 0.3406
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
